// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0zq6Q14RtCZ8HuS9vlJ0IwTF5eqPOaZ0',
    appId: '1:646106660257:web:1e7b0d28a963ad9710dfe0',
    messagingSenderId: '646106660257',
    projectId: 'my-app-dfa3b',
    authDomain: 'my-app-dfa3b.firebaseapp.com',
    storageBucket: 'my-app-dfa3b.firebasestorage.app',
    measurementId: 'G-XFE7QHYHNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDT3Xx5YsH7jo-T5brNWOjBndPaXm4ww',
    appId: '1:646106660257:android:c2c2f8999a123d3b10dfe0',
    messagingSenderId: '646106660257',
    projectId: 'my-app-dfa3b',
    storageBucket: 'my-app-dfa3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0tVT2MY_V9XUNcuXiguJsprcUM5ZcrM',
    appId: '1:646106660257:ios:501bdf9ca694633210dfe0',
    messagingSenderId: '646106660257',
    projectId: 'my-app-dfa3b',
    storageBucket: 'my-app-dfa3b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS0tVT2MY_V9XUNcuXiguJsprcUM5ZcrM',
    appId: '1:646106660257:ios:501bdf9ca694633210dfe0',
    messagingSenderId: '646106660257',
    projectId: 'my-app-dfa3b',
    storageBucket: 'my-app-dfa3b.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0zq6Q14RtCZ8HuS9vlJ0IwTF5eqPOaZ0',
    appId: '1:646106660257:web:4e7058372a595d9710dfe0',
    messagingSenderId: '646106660257',
    projectId: 'my-app-dfa3b',
    authDomain: 'my-app-dfa3b.firebaseapp.com',
    storageBucket: 'my-app-dfa3b.firebasestorage.app',
    measurementId: 'G-RRC731DS64',
  );
}
